Q1.What is a python library?Why do we use Python libraries?

In the programming world, a library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. Other than pre-compiled codes, a library may contain documentation, configuration data, message templates, classes, and values, etc.

A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer.  Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.


When developing large-size programs in Python, maintaining code modularity is essential. To facilitate code maintenance, we divide it into separate parts, which can be reused whenever necessary. This is where modules come into play in Python. Instead of duplicating code across different programs and increasing complexity, we encapsulate commonly used functions within modules. By importing these modules into our programs, we can access their functionality without having to rewrite the code. These interconnected modules are typically stored in libraries, and whenever we require a specific module, we import it from its corresponding library. Python's straightforward syntax simplifies this process; we simply use the import statement to include the desired module.

Q2.What is the difference between Numpy array and List?   

Both NumPy arrays and Python lists are used to store collections of items, but they have distinct differences in terms of functionality, performance, and usage:

1. Type Flexibility
List: Python lists can store elements of different data types in the same list. For example, a list can contain integers, strings, floats, etc.
NumPy Array: NumPy arrays are homogeneous, meaning all elements in a NumPy array must be of the same data type (e.g., all integers, all floats).

2. Performance
List: Python lists are slower for numerical operations because they are flexible and don't have the same level of optimization as NumPy arrays.
NumPy Array: NumPy arrays are optimized for numerical computations and provide faster performance for large datasets. Operations on NumPy arrays are implemented in C, which makes them much faster.

3. Functionality
List: Lists are more flexible and can be easily nested to create lists of lists. They provide many built-in methods for operations like appending, removing, or reversing elements.
NumPy Array: NumPy arrays support a wide range of mathematical operations such as element-wise addition, multiplication, and other mathematical functions. They also support broadcasting, which allows operations between arrays of different shapes in a way that expands one of them to a compatible shape.

4. Memory Usage
List: Python lists are less memory efficient because they store references to objects rather than the objects themselves.
NumPy Array: NumPy arrays are more memory-efficient because they store data in contiguous blocks of memory.

5. Dimensionality
List: Lists are one-dimensional, though you can create lists of lists (or higher dimensions) but with limitations.
NumPy Array: NumPy arrays can be multi-dimensional, supporting matrices (2D arrays), tensors (3D arrays), and higher dimensions natively.

6. Indexing and Slicing
List: Lists support basic slicing and indexing but don’t support advanced slicing, fancy indexing, or conditional filtering.
NumPy Array: NumPy arrays offer advanced indexing, including boolean indexing, slicing, and conditional filtering, which makes them more powerful for data manipulation.

7. Usage
List: Lists are used for general-purpose storage of heterogeneous data. They are commonly used in everyday programming tasks.
NumPy Array: NumPy arrays are primarily used in scientific computing, data analysis, machine learning, and numerical computation tasks where performance is critical.

Q3.Find the shape, size and dimension of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]   

In [2]:
import numpy as np

# Creating the array
array = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

# Finding shape, size, and dimension
shape = array.shape      # Shape of the array
size = array.size        # Total number of elements in the array
dimension = array.ndim   # Number of dimensions of the array

print("The shape of the array is",shape)
print("The size of the array is",size)
print("The dimension of the array is",dimension)


The shape of the array is (3, 4)
The size of the array is 12
The dimension of the array is 2


In [ ]:
Q4.Write python code to access the first row of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]   

In [4]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Access the first row
first_row = arr[0]

print("The first row of the array is",first_row)

The first row of the array is [1 2 3 4]


Q5.How do you access the element at the third row and fourth column from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]  

In [7]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]

print("The element at the third row and fourth column from the given numpy array is ",element)


The element at the third row and fourth column from the given numpy array is  12


Q6.Write code to extract all odd-indexed elements from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Flatten the array into a 1D array
flat_arr = arr.flatten()

# Extract odd-indexed elements
odd_indexed_elements = flat_arr[1::2]

print("The odd indexed elements are: ",odd_indexed_elements)

The odd indexed elements are:  [ 2  4  6  8 10 12]


Q7.How can you generate a random 3x3 matrix with values between 0 and 1?  

In [9]:
import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print(random_matrix)

[[0.09255547 0.18897655 0.71197533]
 [0.13337763 0.54193229 0.06448109]
 [0.15864769 0.56050019 0.6651959 ]]


Q8.Describe the difference between np.random.rand and np.random.randn?

np.random.rand and np.random.randn are both functions in NumPy used to generate random numbers, but they differ in the distribution of the numbers they generate.

1. np.random.rand
Distribution: Generates random numbers from a uniform distribution over the interval [0, 1)
Range:  All values will be between 0 (inclusive) and 1 (exclusive).
Syntax: np.random.rand(d0, d1, ..., dn)
Usage: Often used when you need random numbers within a specific range, typically [0, 1].

2. np.random.randn
Distribution: Generates random numbers from a standard normal distribution (also known as a Gaussian distribution) with a mean of 0 and a standard deviation of 1.
Range: Values are centered around 0, with most values falling between -3 and 3, but not limited to any specific range.
Syntax: np.random.randn(d0, d1, ..., dn)
Usage: Often used in statistical modeling or when you need random numbers that follow a normal distribution.

np.random.rand: Uniform distribution in the range [0, 1).
np.random.randn: Normal distribution with a mean of 0 and standard deviation of 1.

In [ ]:
Q9.Write code to increase the dimension of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]   

In [10]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase the dimension of the array by adding a new axis
# For example, adding a new axis at the beginning (axis=0)
arr_expanded = np.expand_dims(arr, axis=0)

print(arr_expanded)
print("Shape of the new array:", arr_expanded.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape of the new array: (1, 3, 4)


Q10.How to transpose the following array in NumPy?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]  

In [12]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
arr_transposed = np.transpose(arr)

print("The given array is",arr)
print("The transposed array is",arr_transposed)

The given array is [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The transposed array is [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Q11.Consider the following matrix:  Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]  Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]] 

Perform the following operation using Python 
Index wise multiplication 
Matrix multiplication 
Add both the matric 
Subtract matrix B from A
Divide Matrix B by A   


In [13]:
import numpy as np

# Define Matrix A and Matrix B
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A * B
print("Index-wise Multiplication:\n", index_wise_multiplication)

Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [14]:
# Matrix multiplication
matrix_multiplication = np.dot(A, B.T)
print("Matrix Multiplication:\n", matrix_multiplication)

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


In [15]:
# Addition of both matrices
addition = A + B
print("Addition:\n", addition)

Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [16]:
# Subtraction of Matrix B from Matrix A
subtraction = A - B
print("Subtraction:\n", subtraction)

Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [17]:
# Element-wise division of Matrix B by Matrix A
# Ensure that no element in A is zero to avoid division by zero errors
division = B / A
print("Division:\n", division)

Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Q12.Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the .byteswap() method to swap the byte order of an array. This method is used to convert the byte order of the elements in the array, which can be useful for compatibility with different hardware architectures or file formats.

In [18]:
import numpy as np

# Define an array with a specific byte order
arr = np.array([1, 256, 65536], dtype=np.int16)

# Print original array and its byte order
print("Original array:", arr)
print("Original dtype:", arr.dtype)

# Swap byte order
arr_swapped = arr.byteswap().newbyteorder()

# Print the swapped array and its byte order
print("Swapped array:", arr_swapped)
print("Swapped dtype:", arr_swapped.dtype)

Original array: [  1 256   0]
Original dtype: int16
Swapped array: [  1 256   0]
Swapped dtype: >i2


C:\Users\91798\AppData\Local\Temp\ipykernel_23424\1061551182.py:4: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 65536 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr = np.array([1, 256, 65536], dtype=np.int16)


In [ ]:
Q13.What is the significance of the np.linalg.inv function? 

The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. The significance of the inverse of a matrix lies in its application to solving systems of linear equations, matrix equations, and other mathematical and engineering problems.

Key Points of np.linalg.inv():
Matrix Inverse:

The inverse of a matrix 
𝐴
A is a matrix 
𝐴
−
1
A 
−1
  such that when 
𝐴
A is multiplied by 
𝐴
−
1
A 
−1
 , it yields the identity matrix 
𝐼
I: 
𝐴
×
𝐴
−
1
=
𝐼
A×A 
−1
 =I.
Applications:

Solving Linear Systems: If you have a system of linear equations 
𝐴
𝑥
=
𝑏
Ax=b, where 
𝐴
A is a square matrix, you can solve for 
𝑥
x using 
𝑥
=
𝐴
−
1
𝑏
x=A 
−1
 b, provided 
𝐴
A is invertible.
Matrix Equations: In various problems involving matrix equations, the inverse is used to isolate and solve for unknown matrices.
Requirement:

The matrix 
𝐴
A must be square (i.e., the number of rows must equal the number of columns) and invertible (i.e., its determinant must be non-zero) for np.linalg.inv() to compute the inverse. If the matrix is not invertible, np.linalg.inv() will raise a LinAlgError.
Numerical Stability:

Computing the matrix inverse can be numerically unstable for ill-conditioned matrices. In such cases, it is often better to use methods such as np.linalg.solve() for solving systems of linear equations, which can be more stable.

Q14.What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape or dimensions of an existing array without changing its data. It allows you to rearrange the data into a new shape as long as the total number of elements remains the same.

Key Points of np.reshape:
Purpose:

Change Shape: Modify the shape of an array to different dimensions while preserving its data.
Data Arrangement: Rearrange the data into a specified shape, which can be useful for different operations or algorithms that require specific input shapes.
Requirements:

Total Elements: The total number of elements in the original array must match the total number of elements in the reshaped array. If the new shape doesn’t match the total number of elements, NumPy will raise a ValueError.

Syntax:
np.reshape(a, newshape, order='C')



Q15.What is broadcasting in Numpy?  

Broadcasting in NumPy is a powerful mechanism that allows operations on arrays of different shapes and sizes to be performed element-wise without explicitly reshaping the arrays. It simplifies the process of working with arrays of different dimensions by automatically expanding smaller arrays to match the shape of larger ones.

Key Concepts of Broadcasting:
Basic Idea:

Broadcasting allows NumPy to perform element-wise operations on arrays with different shapes. It works by "stretching" the smaller array across the larger array so that they have compatible shapes for the operation.
Rules for Broadcasting: Broadcasting follows a set of rules to determine whether two arrays are compatible:

Rule 1: If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both arrays have the same number of dimensions.
Rule 2: For each dimension, the sizes of the two arrays must either be the same or one of them must be 1. If the sizes are different and neither is 1, broadcasting cannot be performed.
How Broadcasting Works:

When performing an operation on arrays with different shapes, NumPy tries to broadcast the arrays to a common shape. This involves expanding the smaller array along dimensions where it has size 1, so it matches the shape of the larger array.


Broadcasting is a technique in NumPy that allows for element-wise operations on arrays of different shapes.
Rules: The shapes of the arrays must be compatible based on specific broadcasting rules.
Efficiency: Broadcasting avoids unnecessary memory usage by not actually replicating data but instead performing operations as if the smaller array were expanded.
Broadcasting can simplify code and improve performance, especially when working with arrays of different dimensions in scientific computing and data analysis tasks.